description: "To run the server locally, first install the required dependencies:"
services:
  - type: web
    name: rescuex-disaster-assistant
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /api/health